# Generated by Django 3.2.3 on 2021-05-14 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailuser',
            name='birthdate',
        ),
        migrations.RemoveField(
            model_name='emailuser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='emailuser',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='emailuser',
            name='preferred_name',
        ),
        migrations.RemoveField(
            model_name='emailuser',
            name='reset_key',
        ),
        migrations.RemoveField(
            model_name='emailuser',
            name='validated_at',
        ),
        migrations.RemoveField(
            model_name='emailuser',
            name='validation_key',
        ),
    ]
