# Generated by Django 3.2.3 on 2021-06-01 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210514_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailuser',
            name='is_borrower',
            field=models.BooleanField(default=False, help_text='If the user is a borrower or not.'),
        ),
    ]
