# Generated by Django 3.2.6 on 2021-08-31 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_emailuser_is_borrower'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailuser',
            name='is_capital_source_provider',
            field=models.BooleanField(default=False, help_text='If the user provides a capital source or not.'),
        ),
    ]
