database:
  image: postgres
  environment:
    - POSTGRES_USER=sharky
    - POSTGRES_PASSWORD=sharky
backend:
  build: .
  command: bash /sharky/server/django_devserver.sh
  volumes:
  - .:/sharky
  links:
  - database
  ports:
  - "8000:8000"
  environment:
    DB_HOST: database
    PYTHONUNBUFFERED: 1
    DJANGO_SECRET_KEY: b#u+fbl588s)igme)flan_j8lj=@&+-+i!=&m6bg8mv+#0tt##
