# Generated by Django 3.2.3 on 2021-05-14 13:49

import uuid

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('abbreviation', models.CharField(blank=True, max_length=32)),
            ],
            options={
                'verbose_name': 'Bank',
                'verbose_name_plural': 'Banks',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Borrower',
                'verbose_name_plural': 'Borrowers',
                'ordering': ('last_name', 'first_name'),
            },
        ),
        migrations.CreateModel(
            name='CapitalSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('source', models.CharField(choices=[('savings', 'Savings Account'), ('credit_card', 'Credit Card'), ('loan', 'Cash Loan')], max_length=32)),
                ('name', models.CharField(help_text='Reference name of the source account.', max_length=64)),
                ('bank', models.ForeignKey(help_text='The bank in which the capital money came from.', on_delete=django.db.models.deletion.CASCADE, related_name='capital_sources', to='lending.bank')),
            ],
            options={
                'verbose_name': 'Capital Source',
                'verbose_name_plural': 'Capital Sources',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('borrower_name', models.CharField(blank=True, help_text='Name of the actual borrower if known.', max_length=128)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('term', models.PositiveSmallIntegerField(help_text='Term duration in months.')),
                ('payment_schedule', models.CharField(choices=[('monthly', 'Monthly'), ('bi_monthly', 'Bi-monthly')], default='monthly', max_length=32)),
                ('day_deadline', models.PositiveSmallIntegerField(help_text='The day of the month in which the due date will fall.', validators=[django.core.validators.MaxValueValidator(31)])),
                ('is_completed', models.BooleanField(default=False)),
                ('loan_date', models.DateField()),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='lending.borrower')),
            ],
            options={
                'verbose_name': 'Loan',
                'verbose_name_plural': 'Loans',
                'ordering': ('-loan_date',),
            },
        ),
        migrations.CreateModel(
            name='LoanSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=2, help_text='The interest rate from the bank if the source came from credit card or cash loan.', max_digits=5, null=True)),
                ('day_deadline', models.PositiveSmallIntegerField(blank=True, help_text='The day of the month that the due date usually falls if the source came from credit card or cash loan.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('term', models.PositiveSmallIntegerField(blank=True, help_text='The term duration of the loan if the source is credit card or cash loan.', null=True)),
                ('loan_received_date', models.DateField(blank=True, help_text='The date when the loan from the credit card or cash loan was received.', null=True)),
                ('capital_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_sources', to='lending.capitalsource')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='lending.loan')),
            ],
            options={
                'verbose_name': 'Loan Source',
                'verbose_name_plural': 'Loan Sources',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Amortization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=9)),
                ('amort_type', models.CharField(choices=[('full_payment', 'Full Payment'), ('interest_only', 'Interest Only'), ('principal_only', 'Principal Only')], default='full_payment', max_length=32, verbose_name='Amortization Type')),
                ('due_date', models.DateField()),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amortizations', to='lending.loan')),
            ],
            options={
                'verbose_name': 'Amortization',
                'verbose_name_plural': 'Amortization',
                'ordering': ('due_date',),
            },
        ),
    ]
