# Generated by Django 3.2.6 on 2021-08-22 06:07

import uuid

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('abbreviation', models.CharField(blank=True, max_length=32)),
            ],
            options={
                'verbose_name': 'Bank',
                'verbose_name_plural': 'Banks',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Borrower',
                'verbose_name_plural': 'Borrowers',
                'ordering': ('last_name', 'first_name'),
                'unique_together': {('first_name', 'last_name')},
            },
        ),
        migrations.CreateModel(
            name='CapitalSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('source', models.CharField(choices=[('savings', 'Savings Account'), ('credit_card', 'Credit Card'), ('loan', 'Cash Loan')], max_length=32)),
                ('name', models.CharField(help_text='Reference name of the source account.', max_length=64)),
                ('bank', models.ForeignKey(help_text='The bank in which the capital money came from.', on_delete=django.db.models.deletion.CASCADE, related_name='capital_sources', to='lending.bank')),
            ],
            options={
                'verbose_name': 'Capital Source',
                'verbose_name_plural': 'Capital Sources',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('borrower_name', models.CharField(blank=True, help_text='Name of the actual borrower if known.', max_length=128)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('term', models.PositiveSmallIntegerField(help_text='Term duration in months.')),
                ('payment_schedule', models.CharField(choices=[('monthly', 'Monthly'), ('bi_monthly', 'Bi-monthly')], default='monthly', max_length=32)),
                ('first_payment_date', models.DateField(default=django.utils.timezone.now)),
                ('is_completed', models.BooleanField(default=False)),
                ('loan_date', models.DateField()),
                ('borrower', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loans', to=settings.AUTH_USER_MODEL)),
                ('borrower_old', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legacy_loans', to='lending.borrower')),
            ],
            options={
                'verbose_name': 'Loan',
                'verbose_name_plural': 'Loans',
                'ordering': ('-loan_date',),
            },
        ),
        migrations.CreateModel(
            name='LoanSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=2, help_text='The interest rate from the bank if the source came from credit card or cash loan.', max_digits=5, null=True)),
                ('monthly_amortization', models.DecimalField(blank=True, decimal_places=2, help_text='Only applicable if the source comes from any other than savings.', max_digits=9, null=True)),
                ('loan_applied_date', models.DateField(blank=True, help_text='The date when the loan was applied to in the bank.', null=True)),
                ('loan_received_date', models.DateField(blank=True, help_text='The date when the loan from the credit card or cash loan was received.', null=True)),
                ('capital_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_sources', to='lending.capitalsource')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='lending.loan')),
            ],
            options={
                'verbose_name': 'Loan Source',
                'verbose_name_plural': 'Loan Sources',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='LoanSourceAmortization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('due_date', models.DateField()),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='The monthly amortization amount due.', max_digits=9)),
                ('is_preterminated', models.BooleanField()),
                ('pretermindated_interest_rate', models.DecimalField(decimal_places=2, help_text='The interest rate provided by the bank in the case ofpre-termination of the loan.', max_digits=5)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amortizations', to='lending.loansource')),
            ],
            options={
                'verbose_name': 'Loan Source Amortization',
                'verbose_name_plural': 'Loan Source Amortizations',
                'ordering': ('due_date',),
            },
        ),
        migrations.CreateModel(
            name='Amortization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=9)),
                ('amort_type', models.CharField(choices=[('full_payment', 'Full Payment'), ('interest_only', 'Interest Only'), ('principal_only', 'Principal Only')], default='full_payment', max_length=32, verbose_name='Amortization Type')),
                ('due_date', models.DateField()),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('is_preterminated', models.BooleanField(default=False)),
                ('amount_gained', models.DecimalField(decimal_places=2, help_text='Also referred to as the income for this particular loan on a monthly basis.', max_digits=9)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amortizations', to='lending.loan')),
            ],
            options={
                'verbose_name': 'Amortization',
                'verbose_name_plural': 'Amortization',
                'ordering': ('due_date',),
            },
        ),
    ]
