# Generated by Django 3.2.3 on 2021-05-15 06:27

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='first_payment_date',
            field=models.DateField(default=datetime.datetime(2021, 6, 15, 6, 27, 45, 261135, tzinfo=utc)),
        ),
    ]
