# Generated by Django 3.2.6 on 2021-08-24 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loansourceamortization',
            name='pretermindated_interest_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The interest rate provided by the bank in the case ofpre-termination of the loan.', max_digits=5, null=True),
        ),
    ]
