# Generated by Django 3.2.6 on 2021-08-26 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0002_alter_loansourceamortization_pretermindated_interest_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='borrower_old',
        ),
    ]
