# Generated by Django 3.2.3 on 2021-05-15 06:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0002_loan_first_payment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='day_deadline',
        ),
        migrations.AlterField(
            model_name='loan',
            name='first_payment_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
