# Generated by Django 3.2.3 on 2021-05-17 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0004_alter_loansource_loan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loansource',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='loansource',
            name='day_deadline',
        ),
        migrations.RemoveField(
            model_name='loansource',
            name='term',
        ),
    ]
