# Generated by Django 3.2.6 on 2021-08-30 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0004_delete_borrower'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitalsource',
            name='from_third_party',
            field=models.BooleanField(default=False, help_text='If the capital source came from another person other than the owner.'),
        ),
    ]
