# Generated by Django 3.2.3 on 2021-05-17 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0005_auto_20210517_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='amortization',
            name='is_preterminated',
            field=models.BooleanField(default=False),
        ),
    ]
