# Generated by Django 3.2.6 on 2021-08-31 02:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lending', '0005_capitalsource_from_third_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitalsource',
            name='provider',
            field=models.ForeignKey(blank=True, help_text='The third-party provider of the capital source other than the owner. If the provider is the owner, leave this blank.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='capital_sources', to=settings.AUTH_USER_MODEL),
        ),
    ]
