# Generated by Django 3.2.6 on 2021-08-31 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0006_capitalsource_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capitalsource',
            name='from_third_party',
        ),
    ]
