# Generated by Django 3.2.3 on 2021-05-17 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0006_amortization_is_preterminated'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='borrower',
            unique_together={('first_name', 'last_name')},
        ),
    ]
