# Generated by Django 3.2.3 on 2021-05-17 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0007_alter_borrower_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
