# Generated by Django 3.2.3 on 2021-06-01 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0010_auto_20210601_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='borrower',
        ),
    ]
