# Generated by Django 3.2.6 on 2021-08-20 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0012_loan_borrower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loansource',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='lending.loan'),
        ),
    ]
